version: "3.9"
services:
  backend-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks: 
      - fd_mongoose-net
    environment: 
      PORT: 3000
    ports:
      - 3005:3000
    volumes:  
      - ./:/server:ro
    depends_on: 
      - fd_mongo

  fd_mongo:
    image: mongo
    restart: always
    networks: 
      - fd_mongoose-net
    volumes: 
      - /home/user/Documents/mongo_backup:/data/db

networks: 
  fd_mongoose-net:
    name: fd_mongoose-net
